apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: your-namespace  # Replace with your target namespace
spec:
  podSelector: {}  # Selects all pods in the namespace
  policyTypes:
  - Ingress
