apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: joshua-ingress  # Replace with your target namespace
spec:
  podSelector: {}  # Selects all pods in the namespace
  policyTypes:
    - Ingress
