apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          valueFrom:
            secretKeyRef:
              name: secret-q10
              key: db
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: secret-q10
              key: root_pass
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer