apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage
provisioner: kubernetes.io/no-provisioner  
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Delete
  storageClassName: storage
  hostPath:  
    path: /tmp/my-pv  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 4Gi  
  storageClassName: storage  
