apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: syakir-class
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: syakir-class
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: syakir-class