apiVersion: v1
kind: PersistentVolume
metadata:
  name: mock-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mock-storage
  hostPath:
    path: /var/log