apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mock-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: mock-storage