apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: q16-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: q16-sc 