apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
provisioner: csi-driver.example-vendor.example
parameters:
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: Immediate