apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: qq3
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:stable-glibc
          ports:
            - containerPort: 80
