apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q3
  name: q3
spec:
  containers:
  - image: nginx:latest
    name: nginx
    ports:
    - containerPort: 8080
  - image: redis:latest
    name: redis
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}