apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "describe", "delete", "logs"]
controlplane $

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: newuser-pod-binding
  namespace: default
subjects:
- kind: User
  name: newuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
