apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: qq4
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "describe", "logs"]

  -------------------------

  apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: qq4
subjects:
- kind: User
  name: mirza
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
