apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hasbullah-rolebinding
  namespace: default
subjects:
  - kind: User
    name: hasbullah
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io
