apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shamim
  namespace: default
rules:
- apiGroups: [""]
  resources: 
  - pods
  - deployments
  verbs:
  - create
  - get
  - list