apiVersion: v1
kind: Pod
metadata:
  name: myservice-pod
  labels:
    app: myservice
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
