apiVersion: v1
kind: Pod
metadata:
  name: myservice
  labels:
    app: myservice
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    kubernetes.io/role: worker 