apiVersion: v1
kind: Pod
metadata:
  name: syakir-service-pod
  labels:
    app: syakir-service
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80