apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_DATABASE: YWRtaW4=
  MYSQL_PASSWORD: YWRtaW4=
  MYSQL_USER: YWRtaW4=
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sts-0
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  storageClassName: standard
  hostPath:
    path: /tmp/mysql-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sts-1
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  storageClassName: standard
  hostPath:
    path: /tmp/mysql-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sts-2
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 3Gi
  storageClassName: standard
  hostPath:
    path: /tmp/mysql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-mysql-sts-0
spec:
  storageClassName: standard
  volumeName: pv-sts-0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-mysql-sts-1
spec:
  storageClassName: standard
  volumeName: pv-sts-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-mysql-sts-2
spec:
  storageClassName: standard
  volumeName: pv-sts-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  serviceName: "mysql-sts"
  replicas: 3
  selector:
    matchLabels:
      app: mysql-sts
  template:
    metadata:
      labels:
        app: mysql-sts
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
          volumeMounts:
            - name: mysql-pvc
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: standard
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
  selector:
    app: mysql-sts
