# controlplane $ cat q10.yaml
# For Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword"
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==  # base64 encoded "mydatabase"
  MYSQL_PASSWORD: bXlwYXNzd29yZA==  # base64 encoded "mypassword"
  MYSQL_USER: bXl1c2Vy  # base64 encoded "myuser"
# controlplane $

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-secrets
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
