apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlyb290cGFzc3dvcmQ= #myrootpassword
  MYSQL_DATABASE: bXlkYXRhYmFzZQ== #mydatabase
  MYSQL_USER: bXl1c2Vy #myuser
  MYSQL_PASSWORD: bXlwYXNzd29yZA== #mypassword
