apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: test
  MYSQL_DATABASE: test     
  MYSQL_USER: test                  
  MYSQL_PASSWORD: test       
