apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod-web
  namespace: web-frontend
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    - containerPort: 50000
