apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: web-frontend
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:latest
    ports:
    - containerPort: 8080