apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  namespace: web-frontend
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
        - containerPort: 50000
