apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenki
  name: jenki
spec:
  containers:
  - image: jenkins/jenkins:latest
    name: jenki
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
