apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app_env_stage: dev
spec:
  replicas: 6
  selector:
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379