apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-server
  name: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-server
    spec:
      containers:
        - image: nginx:1.18
          name: nginx
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"